### ISSUE TITLE
IPv6 documentation

### ISSUE THREAD

**Issue by vielmetti** [packethost/docs#4]
In this document https://support.packet.com/kb/articles/elastic-ips

Public IPv6 - We assign a (publicly routable) /56 on the project level, which is divisible into 256 /64s (“LAN subnets” in IPv6 parlance), each routable to a server. IPv6 addressing is also provided at no charge.

How is this to be done?

**Comment by kevin-zhaoshuai** [comment]
Yes, we've met several problems when setup the elastic IPs for IPv6.
I've a /56 pools in my projects and I want to reserve a IPv6 pools for my OpenStack clusters to use.

So I come to Elastic IPs. In one machine, whose Network mode is Mixed/Hybrid, I click the "Network" - ”Elastic IPs“ - "assign new Elastic" - "public IPv6" and then I get an Elastic IP pools:

IP / RANGE | TYPE | QUANTITY |  
-- | -- | -- | --
2604:1380:4111:3e02::/64 | Public IPv6 | >2 billion IP(s)

But in the document, I don't find how to setup the network gateway for this type of IP, and how to make IPv6 IP worked. Even configure the IP to an network device, I could not ping to them via another IPv6 IP.

**Comment by kevin-zhaoshuai** [comment]
@zalkar-z Hey guys, do we have plan to produce the doc?

**Comment by zalkar-z** [comment]
@kevin-zhaoshuai yep, working on it! sorry for the delay

**Comment by kevin-zhaoshuai** [comment]
@zalkar-z Let me clarify my requests.
I know that after installation, for example IPv4, it will have a /28 IP and gateway.
So that I have a network gateway and IP range, I can use this for vm instance to use.

For IPv6, now my issue is:
I have a IPv6 IP block, for example 2604:1380:4111:3e02::/64. And I want my VMs provisioned by OpenStack(running on Packet node) to use the IP from the IPv6 Ip block 2604:1380:4111:3e02::/64, But I really don't know how to use it. I don't know which can be served as the network gateway, and I configure 1 IP to a node, but it never worked.
